-- =========================
-- TABLA: ROL
-- =========================
CREATE TABLE ROL (
    ROL_ID SERIAL PRIMARY KEY,
    ROL_NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

COMMENT ON TABLE ROL IS 'Tabla de roles del sistema';
COMMENT ON COLUMN ROL.ROL_ID IS 'Identificador único del rol';
COMMENT ON COLUMN ROL.ROL_NOMBRE IS 'Nombre del rol';

-- =========================
-- TABLA: USUARIO
-- =========================
CREATE TABLE USUARIO (
    USU_ID SERIAL PRIMARY KEY,
    USU_USERNAME VARCHAR(50) NOT NULL UNIQUE,
    USU_CLAVE VARCHAR(255) NOT NULL,
    USU_ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    USU_FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USU_FEC_MOD TIMESTAMP
);

COMMENT ON TABLE USUARIO IS 'Tabla de usuarios del sistema';
COMMENT ON COLUMN USUARIO.USU_ID IS 'Identificador único del usuario';
COMMENT ON COLUMN USUARIO.USU_USERNAME IS 'Nombre de usuario único';
COMMENT ON COLUMN USUARIO.USU_CLAVE IS 'Contraseña del usuario';
COMMENT ON COLUMN USUARIO.USU_ESTADO IS 'Estado del usuario (activo/inactivo)';
COMMENT ON COLUMN USUARIO.USU_FEC_REG IS 'Fecha de registro';
COMMENT ON COLUMN USUARIO.USU_FEC_MOD IS 'Fecha de última modificación';

-- =========================
-- TABLA: USUARIO_ROL
-- =========================
CREATE TABLE USUARIO_ROL (
    USU_ID INT NOT NULL,
    ROL_ID INT NOT NULL,
    PRIMARY KEY (USU_ID, ROL_ID),
    FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID),
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID)
);

COMMENT ON TABLE USUARIO_ROL IS 'Relación entre usuarios y roles';
COMMENT ON COLUMN USUARIO_ROL.USU_ID IS 'Referencia al usuario';
COMMENT ON COLUMN USUARIO_ROL.ROL_ID IS 'Referencia al rol';

-- =========================
-- TABLA: PROVEEDOR
-- =========================
CREATE TABLE PROVEEDOR (
    PRV_ID SERIAL PRIMARY KEY,
    PRV_NOMBRE VARCHAR(100) NOT NULL,
    PRV_CONTACTO VARCHAR(100),
    PRV_ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    PRV_FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRV_FEC_MOD TIMESTAMP
);

COMMENT ON TABLE PROVEEDOR IS 'Tabla de proveedores';
COMMENT ON COLUMN PROVEEDOR.PRV_ID IS 'Identificador del proveedor';
COMMENT ON COLUMN PROVEEDOR.PRV_NOMBRE IS 'Nombre del proveedor';
COMMENT ON COLUMN PROVEEDOR.PRV_CONTACTO IS 'Información de contacto';
COMMENT ON COLUMN PROVEEDOR.PRV_ESTADO IS 'Estado del proveedor';

-- =========================
-- TABLA: PRODUCTO
-- =========================
CREATE TABLE PRODUCTO (
    PRO_ID SERIAL PRIMARY KEY,
    PRV_ID INT NOT NULL,
    PRO_NOMBRE VARCHAR(100) NOT NULL,
    PRO_PRECIO_UNITARIO NUMERIC(10,2) NOT NULL CHECK (PRO_PRECIO_UNITARIO >= 0), -- EL PRECIO UNITARIO NO PUEDE SER NEGATIVO
    PRO_ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    PROD_FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROD_FEC_MOD TIMESTAMP,
    FOREIGN KEY (PRV_ID) REFERENCES PROVEEDOR(PRV_ID)
);

COMMENT ON TABLE PRODUCTO IS 'Tabla de productos';
COMMENT ON COLUMN PRODUCTO.PRO_ID IS 'Identificador del producto';
COMMENT ON COLUMN PRODUCTO.PRV_ID IS 'Proveedor asociado';
COMMENT ON COLUMN PRODUCTO.PRO_NOMBRE IS 'Nombre del producto';
COMMENT ON COLUMN PRODUCTO.PRO_PRECIO_UNITARIO IS 'Precio unitario del producto (>= 0)';
COMMENT ON COLUMN PRODUCTO.PRO_ESTADO IS 'Estado del producto';

-- =========================
-- TABLA: STOCK
-- =========================
CREATE TABLE STOCK (
    STK_ID SERIAL PRIMARY KEY,
    PRO_ID INT NOT NULL UNIQUE,
    STK_CANTIDAD INT NOT NULL CHECK (STK_CANTIDAD >= 0), -- LA CANTIDAD NO PUEDE SER NEGATIVA
    FOREIGN KEY (PRO_ID) REFERENCES PRODUCTO(PRO_ID)
);

COMMENT ON TABLE STOCK IS 'Tabla de control de stock';
COMMENT ON COLUMN STOCK.STK_ID IS 'Identificador del stock';
COMMENT ON COLUMN STOCK.PRO_ID IS 'Producto asociado';
COMMENT ON COLUMN STOCK.STK_CANTIDAD IS 'Cantidad disponible';

-- =========================
-- TABLA: CLIENTE
-- =========================
CREATE TABLE CLIENTE (
    CLI_DUI VARCHAR(10) PRIMARY KEY,
    CLI_ID SERIAL UNIQUE,
    CLI_PRIMER_NOMBRE VARCHAR(50) NOT NULL,
    CLI_SEGUNDO_NOMBRE VARCHAR(50),
    CLI_PRIMER_APELLIDO VARCHAR(50) NOT NULL,
    CLI_SEGUNDO_APELLIDO VARCHAR(50),
    CLI_FECHA_NAC DATE,
    CLI_ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    CLI_FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLI_FEC_MOD TIMESTAMP
);

COMMENT ON TABLE CLIENTE IS 'Tabla de clientes';
COMMENT ON COLUMN CLIENTE.CLI_DUI IS 'Identificación única DUI';
COMMENT ON COLUMN CLIENTE.CLI_ID IS 'ID interno autoincremental';
COMMENT ON COLUMN CLIENTE.CLI_PRIMER_NOMBRE IS 'Primer nombre';
COMMENT ON COLUMN CLIENTE.CLI_SEGUNDO_NOMBRE IS 'Segundo nombre';
COMMENT ON COLUMN CLIENTE.CLI_PRIMER_APELLIDO IS 'Primer apellido';
COMMENT ON COLUMN CLIENTE.CLI_SEGUNDO_APELLIDO IS 'Segundo apellido';
COMMENT ON COLUMN CLIENTE.CLI_FECHA_NAC IS 'Fecha de nacimiento';
COMMENT ON COLUMN CLIENTE.CLI_ESTADO IS 'Estado del cliente';
COMMENT ON COLUMN CLIENTE.CLI_FEC_REG IS 'Fecha de registro';
COMMENT ON COLUMN CLIENTE.CLI_FEC_MOD IS 'Fecha de modificación';

-- =========================
-- TABLA: FACTURA
-- =========================
CREATE TABLE FACTURA (
    FAC_ID VARCHAR(10) PRIMARY KEY,
    USU_ID INT NOT NULL,
    CLI_DUI VARCHAR(10) NOT NULL,
    FAC_FECHA DATE NOT NULL,
    FAC_SUBTOTAL NUMERIC(10,2) NOT NULL CHECK (FAC_SUBTOTAL >= 0), -- EL SUBTOTAL NO PUEDE SER NEGATIVO
    FAC_IVA NUMERIC(4,2) NOT NULL CHECK (FAC_IVA >= 0 AND FAC_IVA <= 1), -- PORCENTAJE DE IVA (ej. 0.13 para 13%)
    FAC_TOTAL NUMERIC(10,2) NOT NULL CHECK (FAC_TOTAL >= 0),
    FAC_FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FAC_FEC_MOD TIMESTAMP,
    FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID),
    FOREIGN KEY (CLI_DUI) REFERENCES CLIENTE(CLI_DUI)
);

COMMENT ON TABLE FACTURA IS 'Tabla de facturas';
COMMENT ON COLUMN FACTURA.FAC_ID IS 'Identificador de factura (ej. F00001)';
COMMENT ON COLUMN FACTURA.USU_ID IS 'Usuario que genera la factura';
COMMENT ON COLUMN FACTURA.CLI_DUI IS 'Cliente asociado';
COMMENT ON COLUMN FACTURA.FAC_FECHA IS 'Fecha de la factura';
COMMENT ON COLUMN FACTURA.FAC_SUBTOTAL IS 'Subtotal de la factura (antes de impuestos) >= 0';
COMMENT ON COLUMN FACTURA.FAC_IVA IS 'DATO PORCENTUAL IVA calculado (ej. 0.13 para 13%) >= 0 AND <= 1';
COMMENT ON COLUMN FACTURA.FAC_TOTAL IS 'Total final >= 0';
COMMENT ON COLUMN FACTURA.FAC_FEC_REG IS 'Fecha de registro';
COMMENT ON COLUMN FACTURA.FAC_FEC_MOD IS 'Fecha de modificación';

-- =========================
-- TABLA: DETALLE_FACTURA
-- =========================
CREATE TABLE DETALLE_FACTURA (
    DET_ID SERIAL PRIMARY KEY,
    FAC_ID VARCHAR(10) NOT NULL,
    PRO_ID INT NOT NULL,
    DET_CANTIDAD INT NOT NULL CHECK (DET_CANTIDAD >= 1), -- LA CANTIDAD NO PUEDE SER MENOR DE 1
    DET_PRECIO_UNITARIO NUMERIC(10,2) NOT NULL CHECK (DET_PRECIO_UNITARIO >= 0), -- EL PRECIO UNITARIO NO PUEDE SER NEGATIVO
    DET_COSTO NUMERIC(10,2) NOT NULL CHECK (DET_COSTO >= 0), -- CANTIDAD * PRECIO_UNITARIO
    FOREIGN KEY (FAC_ID) REFERENCES FACTURA(FAC_ID),
    FOREIGN KEY (PRO_ID) REFERENCES PRODUCTO(PRO_ID),
    UNIQUE (FAC_ID, PRO_ID) -- Evita que un mismo producto se repita en la misma factura
);

COMMENT ON TABLE DETALLE_FACTURA IS 'Detalle de productos por factura';
COMMENT ON COLUMN DETALLE_FACTURA.DET_ID IS 'Identificador del detalle';
COMMENT ON COLUMN DETALLE_FACTURA.FAC_ID IS 'Factura asociada';
COMMENT ON COLUMN DETALLE_FACTURA.PRO_ID IS 'Producto vendido';
COMMENT ON COLUMN DETALLE_FACTURA.DET_CANTIDAD IS 'Cantidad vendida (>= 1)';
COMMENT ON COLUMN DETALLE_FACTURA.DET_PRECIO_UNITARIO IS 'Precio histórico del producto al momento de la venta (>= 0)';
COMMENT ON COLUMN DETALLE_FACTURA.DET_COSTO IS 'Costo total del detalle (Cantidad * Precio Unitario) >= 0';