
# Configurtaciones generales
spring.application.name=SistemaFacturacion
server.port=2100

# Configuración de Conexion a la Base de datos de posgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_milagro_db
spring.datasource.username=adminUES
spring.datasource.password=adminDB

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurar usuario y contraseña para la autenticación básica
spring.security.user.name=usuarioUES
spring.security.user.password=claveUES


