spring.application.name=SistemaFacturacion
server.port=2100

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Manejo de Perfiles
spring.profiles.active=dev-mario
#spring.profiles.active=prod