
# Configurtaciones generales
spring.application.name=SistemaFacturacion

# Configurar usuario y contraseña para la autenticación básica
spring.security.user.name=usuarioUES
spring.security.user.password=claveUES

# Perfil
#spring.profiles.active=dev-david
#spring.profiles.active=dev-mario
#spring.profiles.active=dev-karla
spring.profiles.active=dev-carlos
